---
- name: Start ipsec service
  service: name=ipsec state=started

- name: IPSec reads secrets
  command: ipsec auto --rereadsecrets

- name: Start/load tunnels configuration in ipsec
  register: tun_add
  command: ipsec auto --add "{{ item.conn_name }}"
  with_items:
    - "{{ libreswan_tunnel_configuration }}"

- debug: { var: tun_add }
  tags: start
  
- name: Turn up tunnels configuration
  register: tun_up
  command: ipsec auto --up "{{ item.conn_name }}"
  with_items:
    - "{{ libreswan_tunnel_configuration }}"

- debug: { var: tun_up }
  tags: start

- name: Stop ipsec if `stop_ipsec` is defined
  command: ipsec stop
  when: stop_ipsec|default(False)|bool